In [1]:
import pandas as pd

df = pd.read_csv('records3.csv')
df.head()  # or simply type df and execute the cell

,num_agents,skill_type,network,clustering_coefficient,average_path_length,degree_distribution,degree_histogram,cooperation_proportion,density,assortativity,modularity,edge_weight,iteration
0,400,S++,1,0.194579,1.869937,"[55, 53, 50, 49, 60, 54, 64, 57, 46, 41, 50, 5...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.000000,0.133684,-0.008166,0.242383,"[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...",0
1,400,S++,1,0.297028,1.744825,"[86, 100, 80, 90, 100, 97, 87, 92, 81, 72, 92,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.339426,0.255175,0.012169,0.172606,"[9.7, 9.7, 9.7, 9.7, 9.7, 9.7, 9.7, 9.7, 9.7, ...",1
2,400,S++,1,0.562898,1.480338,"[217, 209, 192, 197, 164, 117, 125, 169, 185, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.463439,0.519662,0.076759,0.078339,"[10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10....",2
3,400,S++,1,0.818955,1.222782,"[317, 292, 285, 271, 191, 96, 90, 185, 265, 24...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.369143,0.777218,0.035827,0.016736,"[9.7, 9.7, 9.7, 9.7, 9.7, 9.7, 9.7, 9.7, 9.7, ...",3
4,400,S++,1,0.915186,1.105201,"[381, 377, 363, 366, 322, 280, 100, 251, 336, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.405034,0.894799,0.011335,0.008609,"[9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, ...",4

In [ ]:
df = pd.read_csv('re.csv')

In [2]:
df2 = pd.read_csv('results3.csv')
df2.head()  # or simply type df and execute the cell

,num_agents,skill_type,network,clustering_coefficient,average_path_length,degree_distribution,degree_histogram,cooperation_proportion,density,assortativity,modularity,edge_weight
0,400,S++,1,"0.19457894126358533, 0.2970275236900204, 0.562...","1.869937343358396, 1.7448245614035087, 1.48033...","55, 53, 50, 49, 60, 54, 64, 57, 46, 41, 50, 55...","0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...","0.0, 0.33942632170978626, 0.4634385895987821, ...","0.1336842105263158, 0.2551754385964912, 0.5196...","-0.00816576555706213, 0.012169435357063937, 0....","0.2423833599857381, 0.17260613855614632, 0.078...","10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10..."
1,400,S,1,"0.19507077384230484, 0.28971212803616103, 0.40...","1.868233082706767, 1.7576817042606516, 1.62761...","50, 56, 49, 51, 59, 52, 55, 48, 65, 67, 63, 50...","0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...","0.0, 0.1964550853749072, 0.2084087500646429, 0...","0.1350375939849624, 0.24231829573934838, 0.372...","-0.013893049212364665, -0.0016991976761297609,...","0.25836517971985895, 0.18788434975276355, 0.13...","10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10..."
2,400,br2,1,"0.1887342685774254, 0.28618605133990377, 0.418...","1.870764411027569, 1.7579573934837092, 1.61609...","52, 60, 57, 52, 49, 51, 60, 56, 47, 54, 60, 63...","0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...","0.0, 0.25262163438828533, 0.23639658296660626,...","0.13264411027568923, 0.24204260651629073, 0.38...","-0.0014855497561861836, 0.004433918340695568, ...","0.24675610697903194, 0.1804648294337276, 0.128...","10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10..."
3,400,manipulator-gf,1,"0.19418699679611964, 0.4083792718237402, 0.843...","1.870501253132832, 1.627155388471178, 1.156578...","52, 54, 49, 59, 48, 47, 54, 59, 51, 65, 56, 49...","0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...","1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...","0.13348370927318295, 0.37284461152882203, 0.84...","-0.008501577178580827, 0.04999648954897954, -0...","0.25811348250950267, 0.13592726720420772, 0.01...","10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10..."
4,400,eeew_simp,1,"0.19463013147500924, 0.28556207404279144, 0.38...","1.8719924812030075, 1.766265664160401, 1.64974...","40, 51, 47, 50, 59, 56, 48, 60, 50, 42, 53, 55...","0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...","0.0, 0.14699205448354144, 0.1911323182500536, ...","0.1324812030075188, 0.233734335839599, 0.35025...","-0.0069825164711825, 0.022146653864746783, 0.0...","0.24748734933690295, 0.1957278341202804, 0.150...","10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10..."